import './globals.css'
import styles from './layout.module.css'
import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'

const inter = Plus_Jakarta_Sans({ subsets: ['latin'],
    style: ["normal"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



const api = process.env.NEXT_PUBLIC_LIBRARY_API

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1  className={styles.header}>Layout</h1>
        {children}</body>
    </html>
  )
}
